Integrate JWT functions
piLinux/GoREST pull request #6
Opened 2020-12-13 22:27 UTC by Paul75

- env : MySigningKey
- add user model password
- router : add JWT to posts actions
- router : add login route

---
name: Pull request
about: Send a pull request to improve the project
title: 'Add JWT implementation'
labels: ''
assignees: ''

---

## Description

Implementation of JWT authentication.
Add password in user model
add login path in route.
```
// login
v1.POST("login", controller.Login)
```
Add JWT in route : for example in posts routes : 
`rPosts.Use(middleware.JWT())`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How has this been tested?
In POSTMAN you can add parameters to JWT and query to login:
In route of login in POST : http://localhost:3000/login
In body  : 
{
    "login":"test@test.fr",
    "pass":"test"
}

It return a token 
{
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJ0ZXN0QHRlc3QuZnIiLCJleHAiOjE2MDc5MDQ4NzYsImlzcyI6Im1vdmllIEFQSSJ9.qIbaYxo_G0rAU8zcwVlVAHW4hEPXgpr_AwJmIXkcnGU"
}

For example of my config of POSTMAN : 
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/457062/102025803-a0fb1700-3d9a-11eb-8d88-c2644fc20377.png">

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warning
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2020-12-16 19:38 UTC, piLinux requested changes
Hi @Paul75 

Thank you a lot for the great work you already did! I would like you to check all the points I mentioned quoting lines of codes from your pull request. If you have any confusion or a better suggestion, kindly post them as well. After fixing these issues, I will merge it as soon as possible.

Thank you.

2020-12-16 19:38 UTC, piLinux commented on controller/login.go
> +	Pass  string `json:"pass"`
To keep it consistent with the existing code patterns, please update it from

```
Login string `json:"login"`
Pass  string `json:"pass"`
```

to this (check the caps-lock):

```
Email string `json:"Email"`
Password  string `json:"Password"`
```

2020-12-16 19:38 UTC, piLinux commented on controller/login.go
> +	u, err := service.GetUserByEmail(payload.Login)
Following the previous review, this should be updated from

`u, err := service.GetUserByEmail(payload.Login)` to 

`u, err := service.GetUserByEmail(payload.Email)`

2020-12-16 19:38 UTC, piLinux commented on controller/login.go
> +	if u.Password != model.HashPass(payload.Pass) {
And here, it will be:

`if u.Password != model.HashPass(payload.Password) {`

2020-12-16 19:38 UTC, piLinux commented on lib/middleware/jwt.go
> +	log.Println("try to pars the JWT")
Spelling error:

Should be `parse`

2020-12-16 19:38 UTC, piLinux commented on lib/middleware/jwt.go
> +	Email string `json:"email"`
Please update the caps-lock to keep consistency in the codebase.

```
	ID    uint   `json:"Id"`
	Email string `json:"Email"`
```

2020-12-16 19:38 UTC, piLinux commented on database/model/user.go
> +	Password string `json:"password"`
Please use caps-lock to keep the same code pattern:

```
Password string `json:"Password"`
```

2020-12-16 19:38 UTC, piLinux commented on database/model/user.go
> +		Posts    []Post `json:"posts"`
Shouldn't they be changed into capital letters as well?

`json:"Id"` etc.

2020-12-16 19:38 UTC, piLinux commented on database/model/user.go
> +		Posts []Post `json:"posts"`
Shouldn't they be changed into capital letters as well?

`json:"Id"` etc.

2020-12-16 19:38 UTC, piLinux commented on main.go
> +		rPosts.DELETE("/:id", controller.DeletePost)
@Paul75 

If you follow the procedure explained in `README`, it isn't possible anymore to create a new user right after cloning the project without omitting these two lines:

```
rUsers.Use(middleware.JWT())
rPosts.Use(middleware.JWT())
```

I would like to hear your feedback on this issue. Here is my suggestion, perhaps it will help you generate a better approach.

- someone clones the project and do the database migration as explained in the `README`
- they create a new user with/without posts (articles) at `/api/v1/register` endpoint
- upon registration, they receive the bearer token
- using the token, they can create more posts (all posts will belong to that specific user)
- they need the token to update or delete any post belong to that user
- at `/api/v1/login` endpoint, anyone can use correct `Email` and `Password` to get a new token
- Endpoints `/api/v1/users` and `/api/v1/posts` should remain public (only `read` or `GET` access, but no email and password must be exposed) so that anyone can easily test both private and public routes without doing any modification of the code.

During my testing of this pull request, I figured out that from endpoints `/api/v1/users` or `/api/v1/users/:id`, it doesn't fetch any post belonged to the users. It should be fixed as well.

Thank you.

2020-12-16 21:59 UTC, Paul75 commented on lib/middleware/jwt.go
> +	log.Println("try to pars the JWT")
Yes you are write

2020-12-17 10:18 UTC, Paul75 commented on main.go
> +		rPosts.DELETE("/:id", controller.DeletePost)
Hello,

If I understand : 
I would like to hear your feedback on this issue. Here is my suggestion, perhaps it will help you generate a better approach.

- they create a new user with/without posts (articles) at /api/v1/register endpoint **===> OK**
- upon registration, they receive the bearer token **===> you mean that when create user without posts, I return token in response ?**
- using the token, they can create more posts (all posts will belong to that specific user) **===> You mean that in body I give param the token ?**
- they need the token to update or delete any post belong to that user **===> OK**
- at /api/v1/login endpoint, anyone can use correct Email and Password to get a new token **===> OK**
- Endpoints /api/v1/users and /api/v1/posts should remain public (only read or GET access, but no email and password must be exposed) so that anyone can easily test both private and public routes without doing any modification of the code. **===> OK**

2020-12-17 11:03 UTC, piLinux commented on main.go
> +		rPosts.DELETE("/:id", controller.DeletePost)
Hi,

upon registration, they receive the bearer token **===> you mean that when create user without posts, I return token in response ?**

- Yes, a new user can be registered (created) with posts or without any post.
- Right after the user is created, a token should be returned. In this way, the user does not need to go through the login process to receive a token.

---

using the token, they can create more posts (all posts will belong to that specific user) **===> You mean that in body I give param the token ?**

- No! The way you already implemented is the best approach (token sent inside the header).
- By this point, I tried to explain the steps: when a user wants to create a new post, he simply uses the token to authorize himself. So, to create a new post, JSON body is:

```
{
    "Title": "title",
    "Body": "message body"
}
```

And the token is sent inside the header, not in the body. And this post will be linked to that specific user.

2020-12-17 12:44 UTC, piLinux requested changes
Please check the comment. This one breaks the primary-foreign relation provided by Gorm v1.

2020-12-17 12:44 UTC, piLinux commented on database/model/user.go
> +	Posts    []Post `gorm:"many2many:user_posts;foreignkey:UserID;association_foreignkey:ID"`
govet issues this warning:
`not compatible with reflect.StructTag.Get: key:"value" pairs not separated by spaces`

But here, the previous one
```
Posts []Post `gorm:"many2many:user_posts";"foreignkey:UserID";"association_foreignkey:ID"`
```
is valid. **Otherwise, Gorm v1 fails to build the primary-foreign key relation properly.**

Note: The original warning is related to space, for example: `json: "Name"` is invalid because of the extra space. But in `gorm:"many2many:user_posts";......`, there is no space inside.

Perhaps, in Gorm v2, it is possible to build the primary-foreign key relation properly using
```
Posts    []Post `gorm:"many2many:user_posts;foreignkey:UserID;association_foreignkey:ID"`
```
which needs to be tested first along with other features before migrating to Gorm v2.

2020-12-17 15:34 UTC, Paul75 commented on database/model/user.go
> +	Posts    []Post `gorm:"many2many:user_posts;foreignkey:UserID;association_foreignkey:ID"`
ok but in my vscode in this line I've got warning "struct field tag `gorm:"many2many:user_posts";"foreignkey:UserID";"association_foreignkey:ID"` not compatible with reflect.StructTag.Get: key:"value" pairs not separated by spaces"

2020-12-17 17:10 UTC, piLinux commented on database/model/user.go
> +	Posts    []Post `gorm:"many2many:user_posts;foreignkey:UserID;association_foreignkey:ID"`
Please check line 20 and 21:

- https://github.com/golangci/govet/blob/44ddbe260190d79165f4150b828650780405d801/testdata/structtag.go#L20
```
I   int `x:"foo",y:"bar"`  // ERROR "not compatible with reflect.StructTag.Get: key:.value. pairs not separated by spaces"
```

- https://github.com/golangci/govet/blob/44ddbe260190d79165f4150b828650780405d801/testdata/structtag.go#L21
```
J   int `x:"foo"y:"bar"`   // ERROR "not compatible with reflect.StructTag.Get: key:.value. pairs not separated by spaces"
```

VScode uses `go vet` as well to examine Go source code and report suspicious constructs. Surprisingly, it confuses `gorm:"many2many:user_posts";"foreignkey:UserID"` with this type `x:"foo",y:"bar"`

2020-12-18 22:02 UTC, merged

2020-12-20 17:40 UTC, piLinux commented on main.go
> +		rPosts.DELETE("/:id", controller.DeletePost)
@Paul75 I am writing the controllers and am going to introduce all three relations this time:
- one to one
- one to many
- many to many

I'll push the commits as soon as I am done with the code and testing. Thank you again for your valuable contribution. For now, I am closing this conversation.

2020-12-20 18:03 UTC, Paul75 commented on main.go
> +		rPosts.DELETE("/:id", controller.DeletePost)
Sorry for not push the controller and router /register because I have now not all my time......

I hope I was helpful.
that mean you do the register ?

Thanks

2020-12-20 19:16 UTC, piLinux commented on main.go
> +		rPosts.DELETE("/:id", controller.DeletePost)
Yes, after analyzing from different perspectives, I am doing it this way:

- Create a new account:
`Auth model`
  - Email
  - password

- Add user info after login:
`User model`
  - First name
  - Last name

- User can create new post and update/delete his own posts only:
`Post model`
  - Title
  - Body

- Many users can have multiple and similar hobbies
`Hobby model`
  - Hobby

**Relations:**
- `Auth model` --> `one-to-zero/one-to-one` --> `User model`
- `User model` --> `one-to-many` --> `Post model`
- `User model` <-- `many-to-many` --> `Hobby model`